import type { FormatDef } from './types';

// =============================================================================
// Biblioteca de formatos. Los dos prompts guía (informática + música) son la
// referencia; aquí vive el CATÁLOGO GRANDE del que el selector elige por tema/canción.
// recomendado_para: ['edu'|'music'] = candidato; [] = "trampa" para que el selector
// lo descarte con motivo (calle, reacción adulta, etc.).
// =============================================================================

// ---- Canal EDUCATIVO (informática para niños, Shorts verticales 15-30s) ----
export const EDU_FORMATS: FormatDef[] = [
  { slug: 'tablero_blanco', nombre: 'Tablero blanco', recomendado_para: ['edu'],
    descripcion: 'El anfitrión dibuja y explica el concepto en una pizarra.',
    estructura: '0-3s hook con pregunta/garabato; desarrollar dibujando paso a paso; revelar la idea con un símbolo; recap + CTA.' },
  { slug: 'con_objetos', nombre: 'Con objetos', recomendado_para: ['edu'],
    descripcion: 'Demostración con juguetes/objetos que hacen tangible la idea.',
    estructura: '0-3s mostrar objeto + promesa; manipular para representar el concepto; resultado visible; pregunta al niño.' },
  { slug: 'ranking', nombre: 'Ranking / Top 3', recomendado_para: ['edu'],
    descripcion: 'Cuenta regresiva de ejemplos del concepto en el mundo del niño.',
    estructura: '0-3s promesa "3 ..."; #3, #2, #1 con ejemplos cotidianos; cierre invitando a aportar el suyo.' },
  { slug: 'texto_sobre_broll', nombre: 'Texto sobre B-roll', recomendado_para: ['edu', 'music'],
    descripcion: 'Texto cinético grande sobre animación/B-roll simple.',
    estructura: '0-3s hook visual + texto que golpea; frases cortas sincronizadas; cierre con la idea en una frase.' },
  { slug: 'hablando_a_camara', nombre: 'Hablando a cámara', recomendado_para: ['edu', 'music'],
    descripcion: 'El anfitrión habla directo al niño, cercano y curioso.',
    estructura: '0-3s pregunta-gancho a cámara; explicar con UNA analogía; un ejemplo; CTA "¡ahora tú!".' },
  { slug: 'clon_duo', nombre: 'Clon dúo (mal vs bien)', recomendado_para: ['edu', 'music'],
    descripcion: 'Pantalla dividida con el anfitrión clonado: "sin X (tedioso)" vs "con X (fácil)".',
    estructura: '0-3s split del contraste; A hace el método lento; B usa el concepto y termina rápido; cierre amable: mismo resultado, menos esfuerzo.' },
  { slug: 'pov', nombre: 'POV (primera persona)', recomendado_para: ['edu'],
    descripcion: 'El niño es el protagonista: "POV: eres una computadora y...".',
    estructura: '0-3s "POV: tú eres ..."; vivir el concepto en primera persona; mini reto; resolución.' },
  { slug: 'antes_despues', nombre: 'Antes / Después', recomendado_para: ['edu', 'music'],
    descripcion: 'Transformación: el problema (antes) y la solución con el concepto (después).',
    estructura: '0-3s "ANTES" caótico/lento; transición; "DESPUÉS" ordenado con el concepto; cierre.' },
  { slug: 'quiz_adivinanza', nombre: 'Quiz / Adivinanza', recomendado_para: ['edu'],
    descripcion: 'Pregunta interactiva con pausa para que el niño responda.',
    estructura: '0-3s pregunta + opciones; "pausa y piensa"; revelar respuesta con celebración; CTA.' },
  { slug: 'sabias_que', nombre: '¿Sabías que…?', recomendado_para: ['edu'],
    descripcion: 'Dato curioso que sorprende y engancha sobre el concepto.',
    estructura: '0-3s "¿Sabías que…?" + dato sorpresa; explicar por qué; ejemplo; cierre "wow".' },
  { slug: 'storytime', nombre: 'Storytime (mini cuento)', recomendado_para: ['edu'],
    descripcion: 'Una mini historia donde el concepto resuelve el problema del personaje.',
    estructura: '0-3s presentar personaje + problema; el concepto entra como héroe; se resuelve; moraleja simple.' },
  { slug: 'eli5', nombre: 'Explícamelo fácil (ELI5)', recomendado_para: ['edu'],
    descripcion: 'El concepto explicado en su forma más simple posible, una frase.',
    estructura: '0-3s "te lo explico en 10 segundos"; UNA analogía clarísima; un ejemplo; "¡ya lo sabes!".' },
  { slug: 'experimento', nombre: 'Experimento / demo', recomendado_para: ['edu'],
    descripcion: 'Demostración tipo experimento que muestra el concepto en acción.',
    estructura: '0-3s "mira esto"; montar el experimento; el resultado revela el concepto; explicación corta.' },
  { slug: 'stop_motion', nombre: 'Stop motion', recomendado_para: ['edu', 'music'],
    descripcion: 'Objetos que cobran vida cuadro a cuadro para mostrar el concepto.',
    estructura: '0-3s objetos que se mueven solos (hook); construir el concepto en movimiento; resultado; cierre.' },
  { slug: 'mito_vs_realidad', nombre: 'Mito vs realidad', recomendado_para: ['edu'],
    descripcion: 'Desmonta una idea equivocada y muestra la correcta.',
    estructura: '0-3s "mucha gente cree que…"; mostrar el mito; ¡pero en realidad…!; verdad clara.' },
  { slug: 'tutorial_paso_a_paso', nombre: 'Tutorial paso a paso', recomendado_para: ['edu'],
    descripcion: 'Pasos numerados muy simples para "hacer" el concepto.',
    estructura: '0-3s "en 3 pasos"; paso 1, 2, 3 con visual claro por paso; resultado final; CTA.' },
  { slug: 'reto_interactivo', nombre: 'Reto interactivo', recomendado_para: ['edu'],
    descripcion: 'Pide al niño pausar e intentar antes de mostrar la solución.',
    estructura: '0-3s plantear el reto; "pausa e intenta"; revelar la solución con el concepto; festejar.' },
  { slug: 'analogia_visual', nombre: 'Analogía visual ("si X fuera Y")', recomendado_para: ['edu'],
    descripcion: 'Metáfora visual potente del mundo del niño para el concepto.',
    estructura: '0-3s "imagina que X es como Y"; desarrollar la analogía visualmente; conectar con lo real; cierre.' },
  { slug: 'tabletop_manos', nombre: 'Mesa cenital (manos)', recomendado_para: ['edu'],
    descripcion: 'Plano cenital de manos manipulando piezas/tarjetas para explicar.',
    estructura: '0-3s manos colocan una pieza clave; armar el concepto sobre la mesa; resultado; CTA.' },
  { slug: 'personaje_narrador', nombre: 'Personaje narrador', recomendado_para: ['edu'],
    descripcion: 'La mascota narra una escena donde aparece el concepto.',
    estructura: '0-3s la mascota entra a una escena; narra el concepto que ocurre ahí; resuelve; invita al siguiente.' },
  { slug: 'loop_satisfactorio', nombre: 'Loop satisfactorio', recomendado_para: ['edu', 'music'],
    descripcion: 'Animación que se repite de forma satisfactoria (refuerza "repetición").',
    estructura: 'Acción que se repite sin costura; el final conecta con el inicio; texto refuerza la idea.' },
  { slug: 'cuenta_regresiva', nombre: 'Cuenta regresiva', recomendado_para: ['edu'],
    descripcion: 'Cuenta atrás de pasos/elementos hasta el clímax del concepto.',
    estructura: '0-3s "en 3… 2… 1…"; cada número revela una parte; clímax con la idea completa.' },
  { slug: 'transicion_magica', nombre: 'Transición mágica', recomendado_para: ['edu', 'music'],
    descripcion: 'Un truco de transición revela el concepto de golpe.',
    estructura: '0-3s build con un gesto (tapar cámara/chasquido); transición; revelar el concepto transformado.' },
  // --- Trampa: descartar para canal infantil ---
  { slug: 'entrevista_calle', nombre: 'Entrevista en la calle', recomendado_para: [],
    descripcion: 'Preguntas a transeúntes adultos.', estructura: 'Abordar gente, reacciones espontáneas.' },
  { slug: 'reaccion_adulta', nombre: 'Reacción adulta', recomendado_para: [],
    descripcion: 'Un adulto reacciona a un clip.', estructura: 'Cara en esquina reaccionando, comentarios.' },
  { slug: 'vlog_dia_a_dia', nombre: 'Vlog del día', recomendado_para: [],
    descripcion: 'Registro disperso sin un concepto único.', estructura: 'Clips del día encadenados.' },
  { slug: 'podcast_clip', nombre: 'Clip de podcast', recomendado_para: [],
    descripcion: 'Fragmento hablado largo de adultos.', estructura: 'Dos personas en micrófonos, charla.' },
];

// ---- Canales de MÚSICA (promo vertical de canciones 15-30s) ----
export const MUSIC_FORMATS: FormatDef[] = [
  { slug: 'hiper_cinematico', nombre: 'Hiper cinemático', recomendado_para: ['music'],
    descripcion: 'Cortes rápidos al beat, alta energía, look premium.',
    estructura: '0-3s build-up + anticipación; drop = corte seco con estallido; cortes cada beat; el plano final repite el inicial (loop).' },
  { slug: 'texto_sobre_broll', nombre: 'Texto/letra sobre B-roll', recomendado_para: ['edu', 'music'],
    descripcion: 'Letra cinética sobre el B-roll del intérprete.',
    estructura: '0-3s B-roll + el gancho de la letra golpea en el drop; frases sincronizadas; cierre loopable.' },
  { slug: 'pantalla_verde', nombre: 'Pantalla verde', recomendado_para: ['music'],
    descripcion: 'El intérprete recortado sobre fondos que cambian al beat.',
    estructura: 'Intérprete sobre fondo neutro cantando el verso fuerte; en el drop el fondo cambia de golpe; cambia por frase; loop.' },
  { slug: 'hablando_a_camara', nombre: 'Hablando a cámara', recomendado_para: ['edu', 'music'],
    descripcion: 'El intérprete invita a escuchar y suelta el gancho.',
    estructura: 'Intro hablada a cámara; en el drop arranca el coro; canta el gancho; CTA a streams.' },
  { slug: 'horizontal_cine', nombre: 'Cine con barras', recomendado_para: ['music'],
    descripcion: 'Look cinematográfico con barras y cámara lenta hacia el drop.',
    estructura: '0-3s cámara lenta con barras; drop = velocidad/color pleno y se abren las barras; coreografía al beat; loop.' },
  { slug: 'clon_duo', nombre: 'Clon dúo', recomendado_para: ['edu', 'music'],
    descripcion: 'Dos intérpretes idénticos en dúo espejo.',
    estructura: '0-3s dos clones en anticipación; drop = saltan juntos al centro; baile espejo al beat; vuelven a la pose inicial (loop).' },
  { slug: 'coreografia_baile', nombre: 'Coreografía / baile', recomendado_para: ['music'],
    descripcion: 'Un paso de baile pegadizo y repetible al ritmo del gancho.',
    estructura: '0-3s presentar el pasito; ejecutarlo en el drop; repetir variando ángulo; invitar a copiarlo.' },
  { slug: 'karaoke_singalong', nombre: 'Karaoke / sing-along', recomendado_para: ['music'],
    descripcion: 'Letra con bolita que rebota para cantar junto.',
    estructura: '0-3s "¡canta conmigo!"; letra aparece sincronizada palabra a palabra; el coro destaca; loop.' },
  { slug: 'lyric_video', nombre: 'Lyric video animado', recomendado_para: ['music'],
    descripcion: 'Tipografía animada que interpreta la letra con movimiento.',
    estructura: '0-3s primera frase fuerte; cada línea con animación tipográfica al beat; clímax en el drop.' },
  { slug: 'loop_perfecto', nombre: 'Loop perfecto', recomendado_para: ['music'],
    descripcion: 'Clip diseñado para repetirse sin costura (el final = el inicio).',
    estructura: 'Acción continua que cierra exactamente donde empezó; el gancho cae en los primeros 3s; loop infinito.' },
  { slug: 'transicion_outfit', nombre: 'Transición (outfit/escena)', recomendado_para: ['music'],
    descripcion: 'Cambios de vestuario/escena sincronizados al beat.',
    estructura: '0-3s primera pose; en cada golpe del drop cambia outfit/escena; final vuelve al inicio (loop).' },
  { slug: 'pov_escenario', nombre: 'POV escenario', recomendado_para: ['music'],
    descripcion: 'Punto de vista del público o del intérprete en el escenario.',
    estructura: '0-3s POV acercándose al escenario; drop = explosión de luces; recorrido al beat; cierre.' },
  { slug: 'detras_camaras', nombre: 'Detrás de cámaras', recomendado_para: ['music'],
    descripcion: 'Cómo se hizo la canción/el personaje (storytelling del artista).',
    estructura: '0-3s un momento real/curioso; mostrar el proceso; conectar con la canción; CTA.' },
  { slug: 'storytelling_artista', nombre: 'Historia del artista', recomendado_para: ['music'],
    descripcion: 'La historia detrás de la canción (la excepción permitida al "no entrevista").',
    estructura: '0-3s gancho emocional/curioso; contar la historia breve; el gancho de la canción la corona; CTA.' },
  { slug: 'mashup_transiciones', nombre: 'Mashup de transiciones', recomendado_para: ['music'],
    descripcion: 'Mezcla veloz de muchas escenas/mundos al ritmo.',
    estructura: '0-3s arranque potente; saltos de escena en cada beat; clímax en el drop; loop.' },
  { slug: 'asmr_visual', nombre: 'ASMR visual / satisfactorio', recomendado_para: ['music'],
    descripcion: 'Visuales satisfactorios sincronizados al beat (colores, partículas).',
    estructura: '0-3s textura/partículas atractivas; cada beat dispara un visual satisfactorio; loop hipnótico.' },
  { slug: 'duet_reaccion', nombre: 'Dueto / colaboración', recomendado_para: ['music'],
    descripcion: 'El intérprete "responde" o acompaña en pantalla dividida.',
    estructura: '0-3s lado A canta; lado B se suma en el drop; juego entre ambos al beat; cierre.' },
  { slug: 'antes_despues', nombre: 'Antes / Después (drop)', recomendado_para: ['edu', 'music'],
    descripcion: 'Build-up tranquilo que estalla en transformación en el drop.',
    estructura: '0-3s escena tranquila/gris (antes); en el drop transformación a color/energía (después); loop.' },
  // --- Trampa: descartar salvo storytelling del artista ---
  { slug: 'tablero_blanco', nombre: 'Tablero blanco', recomendado_para: [],
    descripcion: 'Explicación estática en pizarra.', estructura: 'Dibujar/explicar en pizarra.' },
  { slug: 'entrevista_calle', nombre: 'Entrevista en la calle', recomendado_para: [],
    descripcion: 'Preguntas a transeúntes.', estructura: 'Abordar gente, reacciones.' },
];

export const ALL_FORMATS = { edu: EDU_FORMATS, music: MUSIC_FORMATS };
